nostr-sdk-ffi: fix `uniffi` and add `bindings-android`

diff --git a/bindings/nostr-sdk-ffi/Makefile b/bindings/nostr-sdk-ffi/Makefile
--- a/bindings/nostr-sdk-ffi/Makefile
+++ b/bindings/nostr-sdk-ffi/Makefile
@@ -1,15 +1,49 @@
-# Use 'verbose=1' to echo all commands, for example 'make help verbose=1'.
-ifdef verbose
-  Q :=
-else
-  Q := @
-endif
+SOURCES=$(sort $(wildcard ./src/*.rs ./src/**/*.rs))
 
-uniffideps:
-	$(Q)cargo install uniffi_bindgen --version 0.23
+.PHONY: init
+init:
+	rustup target add aarch64-apple-ios x86_64-apple-ios
+	rustup target add aarch64-apple-darwin x86_64-apple-darwin
+	rustup target add aarch64-apple-ios-sim
+	rustup target add aarch64-linux-android armv7-linux-androideabi i686-linux-android x86_64-linux-android
+	@if [ $$(uname) == "Darwin" ] ; then cargo install cargo-lipo ; fi
+	cargo install cbindgen
+	cargo install cargo-ndk
 
-publish-python: uniffideps python-deps
-	$(Q)maturin publish
+.PHONY: ndk-home
+ndk-home:
+	@if [ ! -d "${ANDROID_NDK_HOME}" ] ; then \
+		echo "Error: Please, set the ANDROID_NDK_HOME env variable to point to your NDK folder" ; \
+		exit 1 ; \
+	fi
 
-python-deps:
-	$(Q)cargo install --locked maturin
+.PHONY: sdk-root
+sdk-root:
+	@if [ ! -d "${ANDROID_SDK_ROOT}" ] ; then \
+		echo "Error: Please, set the ANDROID_SDK_ROOT env variable to point to your SDK folder" ; \
+		exit 1 ; \
+	fi
+
+kotlin: android
+	cargo run --features=uniffi/cli --bin uniffi-bindgen generate src/nostr_sdk.udl --language kotlin --no-format -o ffi/kotlin
+
+android: aarch64-linux-android armv7-linux-androideabi i686-linux-android x86_64-linux-android
+
+aarch64-linux-android: $(SOURCES) ndk-home
+	cargo ndk -t aarch64-linux-android -o ffi/kotlin/jniLibs build --release	
+
+armv7-linux-androideabi: $(SOURCES) ndk-home
+	cargo ndk -t armv7-linux-androideabi -o ffi/kotlin/jniLibs build --release	
+
+i686-linux-android: $(SOURCES) ndk-home
+	cargo ndk -t i686-linux-android -o ffi/kotlin/jniLibs build --release	
+
+x86_64-linux-android: $(SOURCES) ndk-home
+	cargo ndk -t x86_64-linux-android -o ffi/kotlin/jniLibs build --release
+
+bindings-android: sdk-root kotlin
+	cp -r ffi/kotlin/jniLibs bindings-android/lib/src/main
+	cp -r ffi/kotlin/nostr_sdk bindings-android/lib/src/main/kotlin/
+	cd bindings-android && ./gradlew assemble
+	mkdir -p ffi/android
+	cp bindings-android/lib/build/outputs/aar/lib-release.aar ffi/android
